In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("setseries/airbnb-listings-in-california")

Using Colab cache for faster access to the 'airbnb-listings-in-california' dataset.

In [ ]:
import os
import pandas as pd

# List files in the downloaded dataset directory
file_list = os.listdir(path)
print("Files in the dataset directory:", file_list)

Files in the dataset directory: ['California_airbnb.csv']

In [ ]:
# Load California_airbnb.csv
ca_df = pd.read_csv(os.path.join(path, 'California_airbnb.csv'))

In [ ]:
ca_df.head()

,Date,id,scrape_id,name,host_id,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,...,calculated_host_listings_count_shared_rooms,reviews_per_month,bathrooms_text,bedrooms,amenities,host_city,host_country,Country,Zone,City
0,2023-12-10,109,20231203160142,Condo in Culver City,521,2008-06-27,NaN,NaN,50.0,0.0,...,0,0.01,1 bath,2.0,"[""Iron"", ""Cleaning products"", ""Microwave"", ""Fa...",San Francisco,CA,united-states,ca,los-angeles
1,2023-12-10,2708,20231203160142,Rental unit in Los Angeles,3008,2008-09-16,NaN,NaN,100.0,1.0,...,0,0.35,1 bath,1.0,"[""Iron"", ""Fire pit"", ""Self check-in"", ""Cleanin...",Los Angeles,CA,united-states,ca,los-angeles
2,2023-12-10,2732,20231203160142,Rental unit in Santa Monica,3041,2008-09-17,within an hour,100.0,42.0,0.0,...,0,0.16,2 baths,2.0,"[""Sound system"", ""Gas stove"", ""Iron"", ""Drying ...",Santa Monica,CA,united-states,ca,los-angeles
3,2023-12-10,2864,20231203160142,Rental unit in Bellflower,3207,2008-09-25,NaN,NaN,NaN,0.0,...,0,NaN,1 private bath,NaN,"[""Samsung refrigerator"", ""Thermador stainless ...",Bellflower,CA,united-states,ca,los-angeles
4,2023-12-10,63416,20231203160142,Home in Hollywood,309512,2010-12-04,within an hour,100.0,96.0,1.0,...,0,1.02,1.5 shared baths,NaN,"[""Gas stove"", ""Iron"", ""Drying rack for clothin...",Los Angeles,CA,united-states,ca,los-angeles

# Show all the columns in the California Airbnb Dataset

In [ ]:
for column in ca_df:
    print(column)

Date
id
scrape_id
name
host_id
host_since
host_response_time
host_response_rate
host_acceptance_rate
host_is_superhost
host_listings_count
host_total_listings_count
host_has_profile_pic
host_identity_verified
neighbourhood_cleansed
latitude
longitude
property_type
room_type
accommodates
beds
price
minimum_nights
maximum_nights
minimum_minimum_nights
maximum_minimum_nights
minimum_maximum_nights
maximum_maximum_nights
minimum_nights_avg_ntm
maximum_nights_avg_ntm
has_availability
availability_30
availability_60
availability_90
availability_365
calendar_last_scraped
number_of_reviews
number_of_reviews_ltm
number_of_reviews_l30d
first_review
last_review
review_scores_rating
review_scores_accuracy
review_scores_cleanliness
review_scores_checkin
review_scores_communication
review_scores_location
review_scores_value
instant_bookable
calculated_host_listings_count
calculated_host_listings_count_entire_homes
calculated_host_listings_count_private_rooms
calculated_host_listings_count_shared_rooms
reviews_per_month
bathrooms_text
bedrooms
amenities
host_city
host_country
Country
Zone
City

# Gets the Airbnb DataFrame Information

In [ ]:
ca_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247859 entries, 0 to 247858
Data columns (total 62 columns):
 #   Column                                        Non-Null Count   Dtype
---  ------                                        --------------   -----
 0   Date                                          247859 non-null  object
 1   id                                            247859 non-null  int64
 2   scrape_id                                     247859 non-null  int64
 3   name                                          247859 non-null  object
 4   host_id                                       247859 non-null  int64
 5   host_since                                    247829 non-null  object
 6   host_response_time                            201786 non-null  object
 7   host_response_rate                            201786 non-null  float64
 8   host_acceptance_rate                          208292 non-null  float64
 9   host_is_superhost                             226116 non-null  float64
 10  host_listings_count                           247829 non-null  float64
 11  host_total_listings_count                     247829 non-null  float64
 12  host_has_profile_pic                          247829 non-null  float64
 13  host_identity_verified                        247829 non-null  float64
 14  neighbourhood_cleansed                        247859 non-null  object
 15  latitude                                      247859 non-null  float64
 16  longitude                                     247859 non-null  float64
 17  property_type                                 247859 non-null  object
 18  room_type                                     247859 non-null  object
 19  accommodates                                  247859 non-null  int64
 20  beds                                          243387 non-null  float64
 21  price                                         245151 non-null  float64
 22  minimum_nights                                247859 non-null  int64
 23  maximum_nights                                247859 non-null  int64
 24  minimum_minimum_nights                        247853 non-null  float64
 25  maximum_minimum_nights                        247853 non-null  float64
 26  minimum_maximum_nights                        247853 non-null  float64
 27  maximum_maximum_nights                        247853 non-null  float64
 28  minimum_nights_avg_ntm                        247853 non-null  float64
 29  maximum_nights_avg_ntm                        247853 non-null  float64
 30  has_availability                              246466 non-null  float64
 31  availability_30                               247859 non-null  int64
 32  availability_60                               247859 non-null  int64
 33  availability_90                               247859 non-null  int64
 34  availability_365                              247859 non-null  int64
 35  calendar_last_scraped                         247859 non-null  object
 36  number_of_reviews                             247859 non-null  int64
 37  number_of_reviews_ltm                         247859 non-null  int64
 38  number_of_reviews_l30d                        247859 non-null  int64
 39  first_review                                  189554 non-null  object
 40  last_review                                   189554 non-null  object
 41  review_scores_rating                          189599 non-null  float64
 42  review_scores_accuracy                        188995 non-null  float64
 43  review_scores_cleanliness                     188996 non-null  float64
 44  review_scores_checkin                         188971 non-null  float64
 45  review_scores_communication                   188996 non-null  float64
 46  review_scores_location                        188967 non-null  float64
 47  review_scores_value                           188958 non-null  float64
 48  instant_bookable                              247859 non-null  int64
 49  calculated_host_listings_count                247859 non-null  int64
 50  calculated_host_listings_count_entire_homes   247859 non-null  int64
 51  calculated_host_listings_count_private_rooms  247859 non-null  int64
 52  calculated_host_listings_count_shared_rooms   247859 non-null  int64
 53  reviews_per_month                             189554 non-null  float64
 54  bathrooms_text                                247706 non-null  object
 55  bedrooms                                      117828 non-null  float64
 56  amenities                                     247857 non-null  object
 57  host_city                                     193912 non-null  object
 58  host_country                                  195255 non-null  object
 59  Country                                       247859 non-null  object
 60  Zone                                          247859 non-null  object
 61  City                                          247859 non-null  object
dtypes: float64(27), int64(18), object(17)
memory usage: 117.2+ MB

# Dropping Columns to Reduce Noise

In [ ]:
columns_to_drop = [
    "Date",
    "scrape_id",
    "host_id",
    "host_since",
    "host_response_time",
    "host_response_rate",
    "host_acceptance_rate",
    "host_is_superhost",
    "host_listings_count",
    "host_total_listings_count",
    "host_has_profile_pic",
    "host_identity_verified",
    "minimum_minimum_nights",
    "maximum_minimum_nights",
    "minimum_maximum_nights",
    "maximum_maximum_nights",
    "minimum_nights_avg_ntm",
    "maximum_nights_avg_ntm",
    "availability_30",
    "availability_60",
    "availability_90",
    "availability_365",
    "calendar_last_scraped",
    "number_of_reviews_ltm",
    "number_of_reviews_l30d",
    "first_review",
    "last_review",
    "review_scores_accuracy",
    "review_scores_cleanliness",
    "review_scores_checkin",
    "review_scores_communication",
    "review_scores_location",
    "review_scores_value",
    "calculated_host_listings_count",
    "calculated_host_listings_count_entire_homes",
    "calculated_host_listings_count_private_rooms",
    "calculated_host_listings_count_shared_rooms",
    "host_city",
    "host_country",
    "Country",
    "Zone"
]

# Filter out columns that are not present in ca_df
columns_to_drop_existing = [col for col in columns_to_drop if col in ca_df.columns]

clean_df = ca_df.drop(columns=columns_to_drop_existing, errors='ignore')

print("Columns dropped successfully. New shape of clean_df:", clean_df.shape)

Columns dropped successfully. New shape of clean_df: (247859, 21)

In [ ]:
clean_df.head()

,id,name,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,beds,price,...,maximum_nights,has_availability,number_of_reviews,review_scores_rating,instant_bookable,reviews_per_month,bathrooms_text,bedrooms,amenities,City
0,109,Condo in Culver City,Culver City,33.98301,-118.38607,Entire condo,Entire home/apt,6,2.0,129.0,...,730,1.0,2,4.00,0,0.01,1 bath,2.0,"[""Iron"", ""Cleaning products"", ""Microwave"", ""Fa...",los-angeles
1,2708,Rental unit in Los Angeles,Hollywood,34.09625,-118.34605,Private room in rental unit,Private room,1,1.0,94.0,...,550,1.0,40,4.85,1,0.35,1 bath,1.0,"[""Iron"", ""Fire pit"", ""Self check-in"", ""Cleanin...",los-angeles
2,2732,Rental unit in Santa Monica,Santa Monica,34.00440,-118.48095,Private room in rental unit,Private room,1,1.0,179.0,...,27,1.0,24,4.41,0,0.16,2 baths,2.0,"[""Sound system"", ""Gas stove"", ""Iron"", ""Drying ...",los-angeles
3,2864,Rental unit in Bellflower,Bellflower,33.87490,-118.11515,Entire rental unit,Entire home/apt,2,1.0,50.0,...,730,0.0,0,NaN,0,NaN,1 private bath,NaN,"[""Samsung refrigerator"", ""Thermador stainless ...",los-angeles
4,63416,Home in Hollywood,Hollywood Hills,34.11344,-118.32399,Private room in home,Private room,3,2.0,220.0,...,365,1.0,161,4.99,0,1.02,1.5 shared baths,NaN,"[""Gas stove"", ""Iron"", ""Drying rack for clothin...",los-angeles

In [ ]:
print("Possible values for each column in ca_df:\n")
for col in clean_df.columns:
    unique_count = clean_df[col].nunique()
    print(f"Column: {col} (Unique values: {unique_count})")
    if unique_count <= 50:
        print(f"  Unique values: {ca_df[col].unique()}")
    else:
        print("  (Too many unique values to display)")
    print("\n" + "-" * 50 + "\n")

Possible values for each column in ca_df:

Column: id (Unique values: 100365)
  (Too many unique values to display)

--------------------------------------------------

Column: name (Unique values: 10303)
  (Too many unique values to display)

--------------------------------------------------

Column: neighbourhood_cleansed (Unique values: 558)
  (Too many unique values to display)

--------------------------------------------------

Column: latitude (Unique values: 75386)
  (Too many unique values to display)

--------------------------------------------------

Column: longitude (Unique values: 79650)
  (Too many unique values to display)

--------------------------------------------------

Column: property_type (Unique values: 125)
  (Too many unique values to display)

--------------------------------------------------

Column: room_type (Unique values: 4)
  Unique values: ['Entire home/apt' 'Private room' 'Shared room' 'Hotel room']

--------------------------------------------------

Column: accommodates (Unique values: 17)
  Unique values: [ 6  1  2  3  4  5  8 10 12  7 13  9 16 14 11 15  0]

--------------------------------------------------

Column: beds (Unique values: 35)
  Unique values: [ 2.  1.  3.  5.  4. 10. nan  9.  6.  7.  8. 19. 16. 12. 14. 11. 15. 17.
 18. 13. 20. 24. 32. 25. 21. 50. 30. 22. 34. 26. 31. 28.  0. 27. 23. 47.]

--------------------------------------------------

Column: price (Unique values: 2473)
  (Too many unique values to display)

--------------------------------------------------

Column: minimum_nights (Unique values: 140)
  (Too many unique values to display)

--------------------------------------------------

Column: maximum_nights (Unique values: 332)
  (Too many unique values to display)

--------------------------------------------------

Column: has_availability (Unique values: 2)
  Unique values: [ 1.  0. nan]

--------------------------------------------------

Column: number_of_reviews (Unique values: 899)
  (Too many unique values to display)

--------------------------------------------------

Column: review_scores_rating (Unique values: 191)
  (Too many unique values to display)

--------------------------------------------------

Column: instant_bookable (Unique values: 2)
  Unique values: [0 1]

--------------------------------------------------

Column: reviews_per_month (Unique values: 1298)
  (Too many unique values to display)

--------------------------------------------------

Column: bathrooms_text (Unique values: 66)
  (Too many unique values to display)

--------------------------------------------------

Column: bedrooms (Unique values: 25)
  Unique values: [ 2.  1. nan  3.  4.  7.  5.  6.  8. 11.  9. 10. 15. 18. 12. 19. 14. 13.
 24. 16. 23. 32. 50. 20. 17.  0.]

--------------------------------------------------

Column: amenities (Unique values: 209270)
  (Too many unique values to display)

--------------------------------------------------

Column: City (Unique values: 8)
  Unique values: ['los-angeles' 'oakland' 'pacific-grove' 'san-diego' 'san-francisco'
 'san-mateo-county' 'santa-clara-county' 'santa-cruz-county']

--------------------------------------------------

In [ ]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247859 entries, 0 to 247858
Data columns (total 21 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      247859 non-null  int64
 1   name                    247859 non-null  object
 2   neighbourhood_cleansed  247859 non-null  object
 3   latitude                247859 non-null  float64
 4   longitude               247859 non-null  float64
 5   property_type           247859 non-null  object
 6   room_type               247859 non-null  object
 7   accommodates            247859 non-null  int64
 8   beds                    243387 non-null  float64
 9   price                   245151 non-null  float64
 10  minimum_nights          247859 non-null  int64
 11  maximum_nights          247859 non-null  int64
 12  has_availability        246466 non-null  float64
 13  number_of_reviews       247859 non-null  int64
 14  review_scores_rating    189599 non-null  float64
 15  instant_bookable        247859 non-null  int64
 16  reviews_per_month       189554 non-null  float64
 17  bathrooms_text          247706 non-null  object
 18  bedrooms                117828 non-null  float64
 19  amenities               247857 non-null  object
 20  City                    247859 non-null  object
dtypes: float64(8), int64(6), object(7)
memory usage: 39.7+ MB

# Fill beds with bedrooms

In [ ]:
before = clean_df['beds'].isna().sum()

# Fill beds with bedrooms ONLY where beds is NaN
clean_df['beds'] = clean_df['beds'].fillna(clean_df['bedrooms'])

after = clean_df['beds'].isna().sum()

print("Filled:", before - after)

Filled: 2339

In [ ]:
# Drop bedrooms columns
clean_df = clean_df.drop(columns=['bedrooms'])

In [ ]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247859 entries, 0 to 247858
Data columns (total 20 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      247859 non-null  int64
 1   name                    247859 non-null  object
 2   neighbourhood_cleansed  247859 non-null  object
 3   latitude                247859 non-null  float64
 4   longitude               247859 non-null  float64
 5   property_type           247859 non-null  object
 6   room_type               247859 non-null  object
 7   accommodates            247859 non-null  int64
 8   beds                    245726 non-null  float64
 9   price                   245151 non-null  float64
 10  minimum_nights          247859 non-null  int64
 11  maximum_nights          247859 non-null  int64
 12  has_availability        246466 non-null  float64
 13  number_of_reviews       247859 non-null  int64
 14  review_scores_rating    189599 non-null  float64
 15  instant_bookable        247859 non-null  int64
 16  reviews_per_month       189554 non-null  float64
 17  bathrooms_text          247706 non-null  object
 18  amenities               247857 non-null  object
 19  City                    247859 non-null  object
dtypes: float64(7), int64(6), object(7)
memory usage: 37.8+ MB

# Fill beds with accommodates (best proxy)

In [ ]:
# Fill beds with accommodates (best proxy)
clean_df['beds'] = clean_df['beds'].fillna(clean_df['accommodates'])

# Fill missing price with median (robust to outliers)

In [ ]:
# Fill missing price with median (robust to outliers)
clean_df['price'] = clean_df['price'].fillna(clean_df['price'].median())

# # Remove top 1% expensive listings
# upper_limit = clean_df['price'].quantile(0.99)

# clean_df = clean_df[clean_df['price'] <= upper_limit]

# Fill missing ratings with 0 (means no reviews)

In [ ]:
# Fill missing ratings with 0 (means no reviews)
clean_df['review_scores_rating'] = clean_df['review_scores_rating'].fillna(0)

# Fill missing reviews_per_month with 0 (means no reviews)

In [ ]:
# Fill missing reviews_per_month with 0 (means no reviews)
clean_df['reviews_per_month'] = clean_df['reviews_per_month'].fillna(0)

# Fill missing values as 0 for not available for booking

In [ ]:
clean_df['has_availability'] = clean_df['has_availability'].fillna(0).astype(int)

In [ ]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247859 entries, 0 to 247858
Data columns (total 20 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      247859 non-null  int64
 1   name                    247859 non-null  object
 2   neighbourhood_cleansed  247859 non-null  object
 3   latitude                247859 non-null  float64
 4   longitude               247859 non-null  float64
 5   property_type           247859 non-null  object
 6   room_type               247859 non-null  object
 7   accommodates            247859 non-null  int64
 8   beds                    247859 non-null  float64
 9   price                   247859 non-null  float64
 10  minimum_nights          247859 non-null  int64
 11  maximum_nights          247859 non-null  int64
 12  has_availability        247859 non-null  int64
 13  number_of_reviews       247859 non-null  int64
 14  review_scores_rating    247859 non-null  float64
 15  instant_bookable        247859 non-null  int64
 16  reviews_per_month       247859 non-null  float64
 17  bathrooms_text          247706 non-null  object
 18  amenities               247857 non-null  object
 19  City                    247859 non-null  object
dtypes: float64(6), int64(7), object(7)
memory usage: 37.8+ MB

# Clean bathrooms_text

In [ ]:
import re

# Converts text to a clear numeric value
def extract_bathrooms(text):
    if pd.isna(text):
        return None

    match = re.search(r'(\d+\.?\d*)', text)
    if match:
        return float(match.group(1))
    return None

clean_df['bathrooms'] = clean_df['bathrooms_text'].apply(extract_bathrooms)

In [ ]:
clean_df['bathrooms'] = clean_df['bathrooms'].fillna(clean_df['bathrooms'].median())
clean_df = clean_df.drop(columns=['bathrooms_text'])

In [ ]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247859 entries, 0 to 247858
Data columns (total 20 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      247859 non-null  int64
 1   name                    247859 non-null  object
 2   neighbourhood_cleansed  247859 non-null  object
 3   latitude                247859 non-null  float64
 4   longitude               247859 non-null  float64
 5   property_type           247859 non-null  object
 6   room_type               247859 non-null  object
 7   accommodates            247859 non-null  int64
 8   beds                    247859 non-null  float64
 9   price                   247859 non-null  float64
 10  minimum_nights          247859 non-null  int64
 11  maximum_nights          247859 non-null  int64
 12  has_availability        247859 non-null  int64
 13  number_of_reviews       247859 non-null  int64
 14  review_scores_rating    247859 non-null  float64
 15  instant_bookable        247859 non-null  int64
 16  reviews_per_month       247859 non-null  float64
 17  amenities               247857 non-null  object
 18  City                    247859 non-null  object
 19  bathrooms               247859 non-null  float64
dtypes: float64(7), int64(7), object(6)
memory usage: 37.8+ MB

# Clean amenities

*   Create TF-IDF vectorizer
*   Convert amenities into vectors

In [ ]:
clean_df['amenities_clean'] = clean_df['amenities'].str.replace('[{}"]', '', regex=True).fillna('')

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=100, stop_words='english')
amenities_matrix = tfidf.fit_transform(clean_df['amenities_clean'])

In [ ]:
clean_df = clean_df.drop(columns=['amenities'])

In [ ]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247859 entries, 0 to 247858
Data columns (total 20 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      247859 non-null  int64
 1   name                    247859 non-null  object
 2   neighbourhood_cleansed  247859 non-null  object
 3   latitude                247859 non-null  float64
 4   longitude               247859 non-null  float64
 5   property_type           247859 non-null  object
 6   room_type               247859 non-null  object
 7   accommodates            247859 non-null  int64
 8   beds                    247859 non-null  float64
 9   price                   247859 non-null  float64
 10  minimum_nights          247859 non-null  int64
 11  maximum_nights          247859 non-null  int64
 12  has_availability        247859 non-null  int64
 13  number_of_reviews       247859 non-null  int64
 14  review_scores_rating    247859 non-null  float64
 15  instant_bookable        247859 non-null  int64
 16  reviews_per_month       247859 non-null  float64
 17  City                    247859 non-null  object
 18  bathrooms               247859 non-null  float64
 19  amenities_clean         247859 non-null  object
dtypes: float64(7), int64(7), object(6)
memory usage: 37.8+ MB

In [ ]:
clean_df.head()

,id,name,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,beds,price,minimum_nights,maximum_nights,has_availability,number_of_reviews,review_scores_rating,instant_bookable,reviews_per_month,City,bathrooms,amenities_clean
0,109,Condo in Culver City,Culver City,33.98301,-118.38607,Entire condo,Entire home/apt,6,2.0,129.0,30,730,1,2,4.00,0,0.01,los-angeles,1.0,"[Iron, Cleaning products, Microwave, Fast wifi..."
1,2708,Rental unit in Los Angeles,Hollywood,34.09625,-118.34605,Private room in rental unit,Private room,1,1.0,94.0,30,550,1,40,4.85,1,0.35,los-angeles,1.0,"[Iron, Fire pit, Self check-in, Cleaning produ..."
2,2732,Rental unit in Santa Monica,Santa Monica,34.00440,-118.48095,Private room in rental unit,Private room,1,1.0,179.0,7,27,1,24,4.41,0,0.16,los-angeles,2.0,"[Sound system, Gas stove, Iron, Drying rack fo..."
3,2864,Rental unit in Bellflower,Bellflower,33.87490,-118.11515,Entire rental unit,Entire home/apt,2,1.0,50.0,30,730,0,0,0.00,0,0.00,los-angeles,1.0,"[Samsung refrigerator, Thermador stainless ste..."
4,63416,Home in Hollywood,Hollywood Hills,34.11344,-118.32399,Private room in home,Private room,3,2.0,220.0,2,365,1,161,4.99,0,1.02,los-angeles,1.5,"[Gas stove, Iron, Drying rack for clothing, Cl..."

# Gets a CSV file of the clean Dataframe

In [ ]:
clean_df.to_csv('clean_ca_df.csv', index=False)
print('clean_ca_df.csv has been saved.')

clean_ca_df.csv has been saved.